n_runs: 1
experiment: "cger"
data_dir: "../Datasets/BCICompetition-IV2a/"  # ~ replace with your own data path 
dataset_name: 'BCICompIV2a' 
checkpoint: "./checkpoints/cger"
output: ""
approach: 'cger'
ntimes: 1000 
nchans: 22 
n_subjects: 9 
n_classes: 2
use_prototypes: 'yes'
use_memory: "yes"
n_samples:  100
global_reservoir_size: 2000  
e_lr: 0.0005
e_wd: 0.03
wd: 0.01
lr: 0.001 #1.0e-04
lr_patience : 7
lr_factor : 3
patience : 10
inputsize: [288, 22, 1000] 
model: 'DCN'  
units: 175
head_units: 28
latent_dim: 64
hidden_dim: [64, 32]
dropout: 0.25
ks: (1,5)
lr_min: 1.0e-06
batch_size: 32
nepochs: 200
pc_valid: 0.15
pc_test: 0.15
n_splits: 10
n_workers: 1
device: "cuda:0"
